// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN208zfHNCXcKNlV3ugc3A-vP5K-AojY4',
    appId: '1:405972373818:web:f924d43ff55b60fe204003',
    messagingSenderId: '405972373818',
    projectId: 'esports-app-877b3',
    authDomain: 'esports-app-877b3.firebaseapp.com',
    storageBucket: 'esports-app-877b3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpg9ffyak4lnmPs3T1IC29BDipDvd8nnM',
    appId: '1:405972373818:android:9a3c48d691ac7a78204003',
    messagingSenderId: '405972373818',
    projectId: 'esports-app-877b3',
    storageBucket: 'esports-app-877b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDkvm_0WE92p1v8KliF-QfPTAWY3FD4Cg',
    appId: '1:405972373818:ios:1ce2270102128acd204003',
    messagingSenderId: '405972373818',
    projectId: 'esports-app-877b3',
    storageBucket: 'esports-app-877b3.appspot.com',
    iosBundleId: 'com.example.esportsApp',
  );
}
